......F
======================================================================
FAIL: test_should_display_each_number (test_numbers.TestNumbers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 14, in test_should_display_each_number
    self.assertEqual(2, self.display_count)
AssertionError: 2 != 0

----------------------------------------------------------------------
Ran 7 tests in 0.002s

FAILED (failures=1)
