......F.
======================================================================
FAIL: test_should_display_each_number (test_numbers.TestNumbers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/test_numbers.py", line 16, in test_should_display_each_number
    self.assertEqual(2, self.display)
AssertionError: 2 != <bound method TestNumbers.display of <tes[61 chars]ber>>

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=1)
